### ISSUE TITLE
Mettre à jour l'autoload du module.xml

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-adresse-module#53]
```
PHP Fatal error:  Uncaught Exception: Error in autoload configuration -- In /DATAS/lizmap-web-client-3.4.6/lizmap/my-packages/vendor/lizmap/lizmap-adresse-module/adresse//module.xml, this class file doesn't exists: /DATAS/lizmap-web-client-3.4.6/lizmap/my-packages/vendor/lizmap/lizmap-adresse-module/adresse/classes/adresseProfile.class.php in /DATAS/lizmap-web-client-3.4.6/lib/jelix/plugins/configcompiler/nsautoloader/nsautoloader.configcompiler.php:40
Stack trace:
#0 /DATAS/lizmap-web-client-3.4.6/lib/jelix/core/jConfigCompiler.class.php(250): nsautoloaderConfigCompilerPlugin->onModule(Object(stdClass), 'adresse', '/DATAS/lizmap-w...', Object(SimpleXMLElement))
#1 /DATAS/lizmap-web-client-3.4.6/lib/jelix/core/jConfigCompiler.class.php(160): jConfigCompiler::runConfigCompilerPlugins(Object(stdClass))
#2 /DATAS/lizmap-web-client-3.4.6/lib/jelix/core/jConfigCompiler.class.php(85): jConfigCompiler::prepareConfig(Object(stdClass), true, false, '/index.php')
#3 /DATAS/lizmap-web-client-3.4.6/lib/jelix/installer/jInstallerEntryPoint in /DATAS/lizmap-web-client-3.4.6/lib/jelix/plugins/configcompiler/nsautoloader/nsautoloader.configcompiler.php on line 40
```

**Comment by rldhont** [comment]
Le message important: `PHP Fatal error:  Uncaught Exception: Error in autoload configuration -- In adresse//module.xml,  this class file doesn't exists: classes/adresseProfile.class.php`

**Comment by drillinP** [comment]
Commit 2f7b89e5ee56aded843f3d05b6d510132816755e
